name: Deploy to AWS Docker on merge
'on':
  push:
    branches:
      - feat/deployment
      - dev
      - master
jobs:
    build-frontend:
        name: build-frontend
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout
                uses: actions/checkout@v3
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    push: true
                    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/metric-fe:latest
                    context: .
    deploy-to-aws:
        needs: [build-frontend]
        runs-on: ubuntu-latest
        env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        steps:
            -
                name: checkout
                uses: actions/checkout@v2
            -
                name: Copy file via ssh password
                uses: appleboy/scp-action@v0.1.4
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.PRIVATE_KEY }}
                    port: 22
                    source: "docker-compose.yml"
                    target: "/home/ubuntu/metric"
            -
                name: docker compose
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.PRIVATE_KEY }}
                    port: 22
                    script: |
                        export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
                        cd /home/ubuntu/metric
                        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
                        docker compose down
                        docker compose pull
                        docker compose up -d
                        rm -rf /home/ubuntu/metric